name: reflex_application

services:
  postgres:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "postgres"
    volumes:
      - new_postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    image: reflex_app
    container_name: time_management
    depends_on:
      - postgres
    networks:
      - mynetwork
    ports:
      - "3000:3000"
      - "8000:8000"
    stdin_open: true
    tty: true

volumes:
  new_postgres_volume:

networks:
  mynetwork:
    driver: bridge