"""empty message

Revision ID: e97c55096a40
Revises: d0d2393758d2
Create Date: 2024-08-16 07:21:31.503685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e97c55096a40'
down_revision: Union[str, None] = 'd0d2393758d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deligable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.drop_column('is_degibile')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_degibile', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_deligable')

    # ### end Alembic commands ###
